title: 操作票生成助手
version: 0.0.1

LLM_API:
  ERNIEBot:
    api_type: aistudio
    access_token: d825eeefff61b2fa0355228203c7835b3c183add
  ollamaBot:
    api_type: aistudio
    access_token: d825eeefff61b2fa0355228203c7835b3c183add
  DeepseekChat:
    api_type: aistudio
    access_token: d825eeefff61b2fa0355228203c7835b3c183add

DEFAULT_PROMPT: |
  #角色
  -你是一个智能助手，根据规则抽取信息，仅输出答案json格式，无需输出思考过程。
  #提取规则
  1、操作任务，操作任务的规则：将xxx由xx转xx；
  2、设备名称，如：110kV流沙站10kv流沙线FA2 流沙支线#1杆流沙公用台，110kV流沙站10kv流沙线FA2 流沙支线#1杆斗文公用台，110kV流沙站10kv流沙线FA2 流沙支线#1杆1T1开关，110kV流沙站10kv流沙线FA2 流沙支线#1杆32T2开关，110kV流沙站10kv流沙线FA2 流沙支线#1电缆分接箱601开关，110kV流沙站10kv流沙线FA2 流沙支线#1电缆分接箱602开关；
  3、设备类型，判断选项：台区，柱上开关，电缆分接箱开关；例如：【110kV流沙站10kv流沙线FA2#1杆流沙公用台，110kV流沙站10kv流沙线FA2#1杆斗文公用台】应判断为台区，【110kV流沙站10kv流沙线FA2#1杆1T1开关，110kV流沙站10kv流沙线FA2#1杆32T2开关】应判断为柱上开关，【110kV流沙站10kv流沙线FA2 流沙支线#1电缆分接箱601开关，110kV流沙站10kv流沙线FA2 流沙支线#1电缆分接箱602开关】应判断为电缆分接箱开关；
  4、操作前状态，判断选项：运行，热备用，冷备用，检修；
  5、操作后状态，判断选项：运行，热备用，冷备用，检修；
  6、高压刀闸数量，使用阿拉伯数字，如果未提及的则默认为0；
  7、低压刀闸数量，使用阿拉伯数字，如果未提及的则默认为0；
  8、低压开关数量，使用阿拉伯数字，如果未提及的则默认为0；
  9、是否为自动化开关，如果没有提及则默认为否。
  #问题
  -将110kV流沙站10kv流沙线FA2#1杆1T1开关后段线路由运行转检修，有2个低压刀闸，3个低压开关
  #思考分析
  1、操作任务要符合规则：”将110kV流沙站10kv流沙线FA2#1杆1T1开关后段线路由运行转检修“。
  2、设备名称：”110kV流沙站10kv流沙线FA2#1杆1T1开关“；
  3、设备类型：根据设备名称判断设备类型，设备名称为110kV流沙站10kv流沙线FA2#1杆1T1开关，判断为柱上开关。
  4、根据”运行转检修“可得出操作前状态："运行"
  5、根据”运行转检修“可得出操作后状态："检修"
  6、高压刀闸未提及输出0；
  7、低压刀闸数量是2个；
  8、低压开关数量是3个；
  9、是否为自动化开关未提及，输出false；
  # 答案
  {
  "操作任务": "将110kV流沙站10kv流沙线FA2#1杆1T1开关后段线路由运行转检修",
  "设备名称": "110kV流沙站10kv流沙线FA2#1杆1T1开关",
  "设备类型": "柱上开关",
  "操作前状态": "运行",
  "操作后状态": "检修",
  "高压刀闸数量": 0,
  "低压刀闸数量": 2,
  "低压开关数量": 3,
  "是否为自动化开关": false
  }
  # 问题是：$query

upload_dir: assets/raw_upload_files
vector_db_path: assets/db/DefaultVector.db

encoder_batch_size: 16
Encoder:
  ERNIEBot:
    api_type: aistudio
    access_token: d825eeefff61b2fa0355228203c7835b3c183add
#   m3e-small:
#     model_path: assets/models/m3e-small

# text splitter
SENTENCE_SIZE: 200

top_k: 5

Parameter:
  max_length:
    min_value: 0
    max_value: 4096
    default: 1024
    step: 1
    tip: 生成结果时的最大token数
  top_p:
    min_value: 0.0
    max_value: 1.0
    default: 0.7
    step: 0.01
    tip: 用于控制模型生成文本时，选择下一个单词的概率分布的范围。
  temperature:
    min_value: 0.01
    max_value: 1.0
    default: 0.01
    step: 0.01
    tip: 用于调整模型生成文本时的创造性程度，较高的temperature将使模型更有可能生成新颖、独特的文本，而较低的温度则更有可能生成常见或常规的文本
